apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-4565
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/notzipo/express-4565.git'
    targetRevision: HEAD
    path: k8s
  destination:
    name: in-cluster
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
