apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-4565
spec:
  destination:
    name: in-cluster
    namespace: demo
  source:
    path: backend
    repoURL: https://github.com/notzipo/express-4565.git
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
