apiVersion: v1
kind: Service
metadata:
  name: express-4565
  namespace: express-4565
  labels:
    app: express-4565
spec:
  type: NodePort
  selector:
    app: express-4565
  ports:
    - protocol: TCP
      port: 4565
      targetPort: 4565
      nodePort: 30565        # fixed NodePort so it's always reachable at <node-ip>:30565
